### PR TITLE
Resolve #35. Added initial comparative analysis table.

### LINKED ISSUE #35: Comparative analysis
Add table overview of the features competitors already has and identify the gap in the market. Use 3 - 5 competitors. Also include tabletop chess

### PR DESCRIPTION
**Pull request by MadsHeilmann**
Added table

### CODE REVIEW

**Comment by audio-engineer** [comment]
@MadsHeilmann will check later

**Comment by audio-engineer** [comment]
@MadsHeilmann Why don't you just fix the issues found by ChkTeX? They are not that many, the suggestsions are very good, imho, and they are very easy to fix, e.g.: https://tex.stackexchange.com/questions/604017/vertical-rules-in-tables-are-ugly-chktex
This is why linters exist: To assist us developers in writing better code - not to be ignored.

**Comment by audio-engineer** [comment]
@MadsHeilmann Let me know if you need help with the fixes

**Comment by MadsHeilmann** [comment]
> @MadsHeilmann Why don't you just fix the issues found by ChkTeX? They are not that many, the suggestsions are very good, imho, and they are very easy to fix, e.g.: https://tex.stackexchange.com/questions/604017/vertical-rules-in-tables-are-ugly-chktex
> 
> This is why linters exist: To assist us developers in writing better code - not to be ignored.

I will check the link when i am home again tomorrow:)

**Comment by audio-engineer** [comment]
@MadsHeilmann Look at the ChkTeX Action run. It shows you exactly what to change. E.g. the line with the first errors should probably be changed to `\begin{tabular}{ c l l l l l }`:

image

**Review by audio-engineer — APPROVED** [review]

**Review by SebastianMygind — APPROVED** [review]

**Pull request merged**
