### PR TITLE
Add general structure of the state of the art section.

### PR DESCRIPTION
**Pull request by SebastianMygind**
This is just to make the file structure more manageable when more sections are added. This could also be done without the sub-folder, but i do not see how that would be an improvement.

### CODE REVIEW

**Comment by audio-engineer** [comment]
@SebastianMygind You will have to wait until @MadsHeilmann merges his changes - otherwise you will end up with unsolvable merge conflicts due to the difference in structure.

**Comment by audio-engineer** [comment]
@SebastianMygind Also, which issue does this PR solve?

**Review by audio-engineer — CHANGES_REQUESTED** [review]
See comments above

**Comment by SebastianMygind** [comment]
@audio-engineer Will wait.
As for what issues this solves.
This is more preperations to solve the SOTA #11, but it seems a bit convoluted (and annoying) to make an issue for even preparatory steps for issues. Unless we can make a keyword that simply states which isssue you are working on, that does not imply fixing the issue.

**Review by audio-engineer — DISMISSED** [review]

**Review by audio-engineer — APPROVED** [review]

**Review by MadsHeilmann — APPROVED** [review]

**Pull request merged**
