### PR TITLE
Resolve #126, resolve #119. Added section about benefits of a teacher…

### LINKED ISSUE #119: Add section about the benefits of a chess teacher

### LINKED ISSUE #126: Move multiplayer section to the learning section
As pr. Andres advice

### PR DESCRIPTION
**Pull request by MadsHeilmann**
…. Moved multiplayer section in to learning section.

### CODE REVIEW

**Review by audio-engineer — APPROVED** [review]

**Comment by Danar435** [comment]
I don't think that the multiplayer analysis should be in the learning section and I'm pretty sure we discussed this. It is related to learning, yes, but similar to chess engines, it's a big enough topic to be separate from the learning section.

**Comment by SebastianMygind** [comment]
The way the multiplayer section is framed now it would make more sense as a subsection(like this commit).
What you say Kristiyan is also true, but not as it is currently.

**Review by SebastianMygind — APPROVED** [review]

**Comment by MadsHeilmann** [comment]
I sort of disagree as well with you Kristiyan. I think what Andres meant was that the reason we are talking about multiplayer is because of the fact that it enables learning, why it should be under learning. I guess the same can be said for the other sections, so i guess the argument does not really hold. I can change it back if you want to? and then we can hear Andres about it just to make sure :)

**Comment by TexWO** [comment]
I think it’s fine to make the multiplayer section a subsection under learning. We discussed with Andres that our project focuses on learning, not multiplayer. By placing multiplayer as a subsection, we can highlight how it impacts learning among players.

**Review by TexWO — APPROVED** [review]

**Comment by MadsHeilmann** [comment]
As 4 out of 5 agree, i will allow myself to merge. Hope it is alright Kristyian.

**Pull request merged**
